server:
  port: 8888

spring:
  profiles:
    active: dev
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
    typeAliasesPackage: com.megvii.demo.domain
    mapperLocations: classpath:mapper/*.xml
